# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JFactory
email: jfactory@rocketmail.com
description: > # this means to ignore newlines until "baseurl:"
  Come to JFactory for all your drone-video-music, 3D mapping, cross-stitching needs!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jfactory.xyz" # the base hostname & protocol for your site
twitter_username: sleepyjoshua
github_username:  sleepyjoshua

# Build settings
markdown: kramdown

# Collections
collections:
- cross_stitch
